sudo: false

language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

cache: pip

install:
  - pip install coverage detox tox-travis tox-venv

script:
  - coverage erase
  - detox

after_success:
  - coverage combine --append
  - coverage report -m
  - pip install codecov
  - codecov
